#!/usr/bin/env python3
"""Regenerate ATTRIBUTIONS.md from a fresh `pip-licenses` snapshot.

Usage:
    python scripts/generate_attributions.py

The script:
  1. Runs `pip-licenses` with full metadata against the active env.
  2. Writes ATTRIBUTIONS.md sorted alphabetically by package name.
  3. Drops the project itself (`ammp-mcp`) from the list so we don't
     attribute ourselves.

Run after dependency bumps so the attributions stay in sync. CI's audit
workflow regenerates `reports/licenses.json` on every push, but the
markdown file is committed to the repo so casual readers don't have to
download an artefact to see attributions.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ATTRIBUTIONS = REPO_ROOT / "ATTRIBUTIONS.md"
PROJECT_NAME = "ammp-mcp"

HEADER = """# Attributions

[//]: # (This file is generated by scripts/generate_attributions.py from a `pip-licenses` snapshot.)

We gratefully acknowledge the following open-source projects and libraries that `ammp-mcp` builds upon. Thank you to all the contributors who made this possible.

"""


def run_pip_licenses() -> list[dict[str, str]]:
    """Invoke `pip-licenses` and return its parsed JSON."""
    cmd = [
        sys.executable,
        "-m",
        "piplicenses",
        "--format=json",
        "--with-authors",
        "--with-urls",
        "--with-description",
        "--with-license-file",
        "--no-license-path",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        # Fall back to invoking the entry-point directly
        result = subprocess.run(
            ["pip-licenses", *cmd[2:]],
            capture_output=True,
            text=True,
            check=True,
        )
    return json.loads(result.stdout)


def render(rows: list[dict[str, str]]) -> str:
    """Format the rows into a sorted ATTRIBUTIONS.md body."""
    pieces = [HEADER]
    rows = [r for r in rows if r["Name"].lower() != PROJECT_NAME]
    rows.sort(key=lambda r: r["Name"].lower())
    for r in rows:
        name = r["Name"]
        version = r.get("Version", "?")
        lic = (r.get("License") or "?").strip() or "?"
        desc = (r.get("Description") or "").strip()
        url = (r.get("URL") or "").strip()
        author = (r.get("Author") or "").strip()
        license_text = (r.get("LicenseText") or "").strip()

        pieces.append(f"## {name} ({version}) — {lic}\n")
        if desc and desc.lower() not in {"unknown", "no description"}:
            pieces.append(desc + "\n")
        meta = []
        if url and url.lower() != "unknown":
            meta.append(f"* URL: {url}")
        if author and author.lower() != "unknown":
            meta.append(f"* Author(s): {author}")
        if meta:
            pieces.append("\n".join(meta) + "\n")
        if license_text and license_text.lower() != "unknown":
            pieces.append("### License Text\n")
            pieces.append("```\n" + license_text + "\n```\n")
        pieces.append("")
    return "\n".join(pieces).rstrip() + "\n"


def main() -> None:
    rows = run_pip_licenses()
    body = render(rows)
    ATTRIBUTIONS.write_text(body, encoding="utf-8")
    print(f"Wrote {ATTRIBUTIONS} — {len(rows)} packages.")


if __name__ == "__main__":
    main()
