#!/usr/bin/env python3
"""Regenerate ``ATTRIBUTIONS.md`` from a fresh ``pip-licenses`` snapshot.

Usage:
    python scripts/generate_attributions.py

Mirrors the format used by ``aignostics/python-sdk`` (``noxfile.py`` →
``_generate_attributions``) — a flat markdown file with one ``## name
(version) — License`` heading per dependency, the description, URL,
author/maintainer lines, and a fenced code block containing the full
license text.

This script:

  1. Calls ``pip-licenses`` against the active env, capturing description,
     author, maintainer, URL, license name, license file text, and notice
     file text in a single JSON pass.
  2. Drops the project itself (``ammp-mcp``) so we don't attribute
     ourselves.
  3. Sanitises any backtick runs inside license text so the surrounding
     markdown code fence doesn't break.
  4. Writes ``ATTRIBUTIONS.md`` and ``reports/licenses.json``.

Run after dependency bumps. The CI audit workflow regenerates
``reports/licenses.json`` on every push, but the markdown file is
committed so casual readers don't have to download a workflow artefact
to see attributions.
"""

from __future__ import annotations

import html
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ATTRIBUTIONS = REPO_ROOT / "ATTRIBUTIONS.md"
REPORTS_DIR = REPO_ROOT / "reports"
LICENSES_JSON = REPORTS_DIR / "licenses.json"
PROJECT_NAME = "ammp-mcp"

HEADER = """# Attributions

<!-- Generated by scripts/generate_attributions.py from reports/licenses.json.
     Re-run after dependency bumps. -->

We gratefully acknowledge the following open-source projects and libraries that `ammp-mcp` builds upon. Thank you to all the contributors who made this possible.

Each entry below lists the package name, version, license, description, upstream URL, and author(s). The full text of each license is linked via the SPDX identifier rather than embedded — this keeps the file under GitHub's markdown-rendering size threshold while preserving complete attribution metadata. NOTICE files (where shipped by the upstream package, mandated by Apache-2.0 §4) are reproduced verbatim.
"""

# License-name → SPDX-identifier mapping. Best-effort; unmapped license names
# render without an SPDX URL. Source of canonical IDs: https://spdx.org/licenses/.
_SPDX = {
    "MIT License": "MIT",
    "MIT": "MIT",
    "BSD License": "BSD-3-Clause",  # ambiguous; BSD-3-Clause is the typical pip-licenses fallback
    "BSD": "BSD-3-Clause",
    "BSD-3-Clause": "BSD-3-Clause",
    "BSD-2-Clause": "BSD-2-Clause",
    "BSD 3-Clause License": "BSD-3-Clause",
    "Apache Software License": "Apache-2.0",
    "Apache 2.0": "Apache-2.0",
    "Apache-2.0": "Apache-2.0",
    "Apache License 2.0": "Apache-2.0",
    "Apache License, Version 2.0": "Apache-2.0",
    "ISC License (ISCL)": "ISC",
    "ISC License": "ISC",
    "ISC": "ISC",
    "Mozilla Public License 2.0 (MPL 2.0)": "MPL-2.0",
    "MPL 2.0": "MPL-2.0",
    "MPL-2.0": "MPL-2.0",
    "GNU Lesser General Public License v3 (LGPLv3)": "LGPL-3.0-or-later",
    "LGPL-3.0-or-later": "LGPL-3.0-or-later",
    "LGPL": "LGPL-3.0-or-later",
    "GNU General Public License v3 (GPLv3)": "GPL-3.0-or-later",
    "GPL-3.0-or-later": "GPL-3.0-or-later",
    "Python Software Foundation License": "PSF-2.0",
    "PSF": "PSF-2.0",
    "PSF-2.0": "PSF-2.0",
    "The Unlicense (Unlicense)": "Unlicense",
    "Unlicense": "Unlicense",
    "Public Domain": "CC-PDDC",
    "CC0 1.0 Universal (CC0 1.0) Public Domain Dedication": "CC0-1.0",
    "CC0-1.0": "CC0-1.0",
    "Artistic License": "Artistic-2.0",
    "Zlib": "Zlib",
    "WTFPL": "WTFPL",
}


def _spdx_link(license_name: str) -> str | None:
    """Map a pip-licenses license name to its SPDX-license URL.

    Returns ``None`` for unmapped license names so the caller can fall back
    to rendering the literal name without a link.
    """
    key = license_name.strip()
    spdx_id = _SPDX.get(key)
    if spdx_id is None:
        # Try a case-insensitive fallback.
        for k, v in _SPDX.items():
            if k.lower() == key.lower():
                spdx_id = v
                break
    if spdx_id is None:
        return None
    return f"https://spdx.org/licenses/{spdx_id}.html"


def run_pip_licenses() -> list[dict[str, str]]:
    """Invoke ``pip-licenses`` and return its parsed JSON output."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        "-m",
        "piplicenses",
        "--with-authors",
        "--with-maintainers",
        "--with-urls",
        "--with-description",
        "--with-license-file",
        "--with-notice-file",
        "--no-license-path",
        "--format=json",
        "--output-file",
        str(LICENSES_JSON),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        # Older pip-licenses versions don't expose `python -m piplicenses`;
        # fall back to the entry-point. `check=True` raises on failure;
        # we don't read the result because the JSON is written to disk.
        subprocess.run(
            ["pip-licenses", *cmd[2:]],
            capture_output=True,
            text=True,
            check=True,
        )
    return json.loads(LICENSES_JSON.read_text(encoding="utf-8"))


def _format_package(pkg: dict[str, str]) -> str:
    """Format one package entry.

    Layout per package: H2 with name+version+license, then description, then a
    bullet list with URL / authors / maintainers / SPDX link, then the verbatim
    NOTICE file if the upstream package shipped one (Apache-2.0 §4 mandate).

    The license *body* itself is deliberately NOT embedded — historical
    practice was to inline every license text and that pushed ATTRIBUTIONS.md
    past GitHub's ~500 KB markdown-rendering threshold, so GitHub started
    serving the file as wall-of-text instead of parsing it. SPDX-URL
    references satisfy attribution metadata for most permissive licenses;
    only NOTICE files are legally required to be reproduced verbatim.
    """
    name = pkg.get("Name", "Unknown")
    version = pkg.get("Version", "Unknown")
    license_name = (pkg.get("License") or "Unknown").strip() or "Unknown"
    description = (pkg.get("Description") or "").strip()
    url = (pkg.get("URL") or "").strip()
    authors = (pkg.get("Author") or "").strip()
    maintainers = (pkg.get("Maintainer") or "").strip()
    # pip-licenses sometimes hands us HTML-escaped notice bodies (e.g. the
    # Apache-2.0 NOTICE that ships with aiofile contains literal `&lt;…&gt;`
    # for an autolink URL). Unescape before rendering so the code fence shows
    # the original text, not the entity-escaped form.
    notice_text = html.unescape((pkg.get("NoticeText") or "").strip())

    out = f"## {name} ({version}) — {license_name}\n\n"

    if description and description.upper() != "UNKNOWN":
        out += description + "\n\n"

    if url and url.upper() != "UNKNOWN":
        out += f"* URL: {url}\n"
    if authors and authors.upper() != "UNKNOWN":
        out += f"* Author(s): {authors}\n"
    if maintainers and maintainers.upper() != "UNKNOWN":
        out += f"* Maintainer(s): {maintainers}\n"
    spdx_url = _spdx_link(license_name)
    if spdx_url:
        out += f"* License text: [{license_name}]({spdx_url})\n"
    out += "\n"

    if notice_text and notice_text.upper() != "UNKNOWN":
        # Sanitise any embedded triple-backticks so the outer code fence stays intact.
        sanitised = notice_text.replace("```", "~~~")
        out += "### Notice\n\n"
        out += f"```\n{sanitised}\n```\n\n"

    return out


def render(rows: list[dict[str, str]]) -> str:
    rows = [r for r in rows if r.get("Name", "").lower() != PROJECT_NAME]
    rows.sort(key=lambda r: r.get("Name", "").lower())
    body = HEADER + "\n"
    for pkg in rows:
        body += _format_package(pkg)
    # Right-strip per line + collapse trailing blank lines + ensure exactly
    # one final newline. Stays hook-clean across regenerations.
    lines = [line.rstrip() for line in body.splitlines()]
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def main() -> None:
    rows = run_pip_licenses()
    body = render(rows)
    ATTRIBUTIONS.write_text(body, encoding="utf-8")
    print(f"Wrote {ATTRIBUTIONS} — {len(rows)} packages.")


if __name__ == "__main__":
    main()
