#!/usr/bin/env python3
"""Regenerate ``ATTRIBUTIONS.md`` from a fresh ``pip-licenses`` snapshot.

Usage:
    python scripts/generate_attributions.py

Mirrors the format used by ``aignostics/python-sdk`` (``noxfile.py`` →
``_generate_attributions``) — a flat markdown file with one ``## name
(version) — License`` heading per dependency, the description, URL,
author/maintainer lines, and a fenced code block containing the full
license text.

This script:

  1. Calls ``pip-licenses`` against the active env, capturing description,
     author, maintainer, URL, license name, license file text, and notice
     file text in a single JSON pass.
  2. Drops the project itself (``ammp-mcp``) so we don't attribute
     ourselves.
  3. Sanitises any backtick runs inside license text so the surrounding
     markdown code fence doesn't break.
  4. Writes ``ATTRIBUTIONS.md`` and ``reports/licenses.json``.

Run after dependency bumps. The CI audit workflow regenerates
``reports/licenses.json`` on every push, but the markdown file is
committed so casual readers don't have to download a workflow artefact
to see attributions.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ATTRIBUTIONS = REPO_ROOT / "ATTRIBUTIONS.md"
REPORTS_DIR = REPO_ROOT / "reports"
LICENSES_JSON = REPORTS_DIR / "licenses.json"
PROJECT_NAME = "ammp-mcp"

HEADER = """# Attributions

[//]: # (This file is generated by scripts/generate_attributions.py from reports/licenses.json — re-run after dependency bumps.)

We gratefully acknowledge the following open-source projects and libraries that `ammp-mcp` builds upon. Thank you to all the contributors who made this possible.
"""


def run_pip_licenses() -> list[dict[str, str]]:
    """Invoke ``pip-licenses`` and return its parsed JSON output."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        "-m",
        "piplicenses",
        "--with-authors",
        "--with-maintainers",
        "--with-urls",
        "--with-description",
        "--with-license-file",
        "--with-notice-file",
        "--no-license-path",
        "--format=json",
        "--output-file",
        str(LICENSES_JSON),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        # Older pip-licenses versions don't expose `python -m piplicenses`;
        # fall back to the entry-point.
        proc = subprocess.run(
            ["pip-licenses", *cmd[2:]],
            capture_output=True,
            text=True,
            check=True,
        )
    return json.loads(LICENSES_JSON.read_text(encoding="utf-8"))


def _format_package(pkg: dict[str, str]) -> str:
    """Format one package entry — same structure as aignostics/python-sdk."""
    name = pkg.get("Name", "Unknown")
    version = pkg.get("Version", "Unknown")
    license_name = (pkg.get("License") or "Unknown").strip() or "Unknown"
    description = (pkg.get("Description") or "").strip()
    url = (pkg.get("URL") or "").strip()
    authors = (pkg.get("Author") or "").strip()
    maintainers = (pkg.get("Maintainer") or "").strip()
    license_text = (pkg.get("LicenseText") or "").strip()
    notice_text = (pkg.get("NoticeText") or "").strip()

    out = f"## {name} ({version}) — {license_name}\n\n"

    if description and description.upper() != "UNKNOWN":
        out += description + "\n\n"

    if url and url.upper() != "UNKNOWN":
        out += f"* URL: {url}\n"
    if authors and authors.upper() != "UNKNOWN":
        out += f"* Author(s): {authors}\n"
    if maintainers and maintainers.upper() != "UNKNOWN":
        out += f"* Maintainer(s): {maintainers}\n"
    out += "\n"

    if license_text and license_text.upper() != "UNKNOWN":
        # Sanitise any embedded triple-backticks so the outer code fence stays intact.
        sanitised = license_text.replace("```", "~~~")
        out += "### License Text\n\n"
        out += f"```\n{sanitised}\n```\n\n"

    if notice_text and notice_text.upper() != "UNKNOWN":
        sanitised = notice_text.replace("```", "~~~")
        out += "### Notice\n\n"
        out += f"```\n{sanitised}\n```\n\n"

    return out


def render(rows: list[dict[str, str]]) -> str:
    rows = [r for r in rows if r.get("Name", "").lower() != PROJECT_NAME]
    rows.sort(key=lambda r: r.get("Name", "").lower())
    body = HEADER + "\n"
    for pkg in rows:
        body += _format_package(pkg)
    # Right-strip per line so the pre-commit hygiene hook doesn't need to "fix" us.
    body = "\n".join(line.rstrip() for line in body.splitlines()) + "\n"
    return body


def main() -> None:
    rows = run_pip_licenses()
    body = render(rows)
    ATTRIBUTIONS.write_text(body, encoding="utf-8")
    print(f"Wrote {ATTRIBUTIONS} — {len(rows)} packages.")


if __name__ == "__main__":
    main()
