"""First-run setup helpers — backing the `ammp system setup` wizard.

Split out as discrete helpers so the orchestrating command (`setup` in
`_cli.py`) stays well under SonarCloud's S3776 cognitive-complexity
limit (15).

`bootstrap_ammp_dir` is the load-bearing entry point: idempotent,
package-data driven, callable both from the wizard and from
`ammp serve`'s auto-bootstrap path. The wizard adds the interactive
backend prompts and mints a first mentee on top.
"""

from __future__ import annotations

import datetime as dt
import json
import logging
import secrets
import shutil
import subprocess
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt

from .._data import example_mentor_path
from ..mentee import Mentee, hash_api_key, load_mentees, save_mentees
from ..mentor import Mentor, load_mentors
from ..settings import Settings

console = Console()
logger = logging.getLogger(__name__)

_ICON_OK = "[green]✓[/green]"
_VALID_BACKEND_KINDS = {"openclaw", "anthropic", "stub"}


def bootstrap_ammp_dir(s: Settings, *, quiet: bool = False) -> bool:
    """Create `<AMMP_DIR>/` and copy the example mentor in, idempotently.

    Safe to call on every server boot — exits early when the tree
    already has at least one mentor and a `config.env`. Will NOT touch
    ``mentors_root`` if the operator has pointed it somewhere other
    than ``<AMMP_DIR>/mentors`` (e.g. an Obsidian vault); the example
    mentor only ships into the default location, never into
    operator-curated paths.

    Args:
        s: Settings whose `ammp_dir` / `mentors_root` define the tree.
        quiet: When True, suppress informational console output (used
            by `ammp serve`'s auto-bootstrap so the boot log stays
            clean).

    Returns:
        ``True`` when bootstrap created or wrote at least one thing;
        ``False`` when the tree was already fully set up and nothing
        changed.
    """
    ammp_dir = s.ammp_dir
    mentors_root = s.mentors_root
    config_env = ammp_dir / "config.env"
    mentors_is_default = mentors_root.resolve() == (ammp_dir / "mentors").resolve()

    needs_dir = not ammp_dir.exists()
    needs_example = mentors_is_default and not (mentors_root / "example").is_dir()
    needs_config = not config_env.exists()

    changed = False
    if needs_dir or needs_example or needs_config:
        ammp_dir.mkdir(parents=True, exist_ok=True)
        changed = True

    if needs_example:
        mentors_root.mkdir(parents=True, exist_ok=True)
        src = example_mentor_path()
        dst = mentors_root / "example"
        shutil.copytree(src, dst, dirs_exist_ok=True)
        if not quiet:
            console.print(f"{_ICON_OK} Copied shipped example mentor → [bold]{dst}[/bold]")

    if needs_config:
        # Minimal scaffold. The wizard will fill in backend secrets etc.
        lines = [
            "# ammp-mcp config — auto-generated by bootstrap on first run.",
            f"# Generated {dt.datetime.now(dt.UTC).isoformat()}.",
            "# Edit freely, or re-run `ammp setup` to regenerate interactively.",
            "",
            f"AMMP_DIR={ammp_dir}",
            f"AMMP_MENTORS_ROOT={mentors_root}",
            f"AMMP_MENTEES_FILE={s.mentees_file}",
            f"AMMP_AUDIT_LOG_PATH={s.audit_log_path}",
            "AMMP_REQUIRE_AUTH=false",
            "",
        ]
        config_env.write_text("\n".join(lines), encoding="utf-8")
        if not quiet:
            console.print(f"{_ICON_OK} Wrote [bold]{config_env}[/bold]")

    # Marketplace caches hold the skill bodies. Clone any the corpus
    # references that aren't on disk yet — independent of the scaffold
    # above, since a fully-configured host can still be missing them.
    if bootstrap_marketplaces(s, quiet=quiet):
        changed = True

    return changed


def _referenced_marketplaces(mentors_root: Path) -> set[str]:
    """Collect marketplace names referenced by `plugin` fields in the corpus.

    Walks every ``<mentor>/playbooks/<playbook>/playbook.json`` under
    ``mentors_root`` and extracts the ``@<marketplace>`` suffix of each
    ``plugin`` reference.

    Args:
        mentors_root: Root directory holding one subdirectory per mentor.

    Returns:
        The distinct set of referenced marketplace names (may be empty).
    """
    names: set[str] = set()
    for pb_json in sorted(mentors_root.glob("*/playbooks/*/playbook.json")):
        try:
            data = json.loads(pb_json.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        plugin = data.get("plugin", "")
        if isinstance(plugin, str) and "@" in plugin:
            names.add(plugin.rsplit("@", 1)[1])
    return names


def bootstrap_marketplaces(s: Settings, *, quiet: bool = False) -> bool:
    """Clone marketplaces the corpus references into ``marketplaces_root``.

    Idempotent: a marketplace already on disk is left untouched. A
    referenced marketplace with no URL in ``s.marketplace_repos``, or a
    clone that fails (private repo without auth, no network), logs a
    warning and is skipped — the server still boots and falls back to
    local skills for that playbook.

    Args:
        s: Settings supplying ``mentors_root``, ``marketplaces_root`` and
            the ``marketplace_repos`` name → URL map.
        quiet: When True, suppress the per-clone success line; warnings
            are logged regardless.

    Returns:
        ``True`` when at least one marketplace was cloned.
    """
    referenced = _referenced_marketplaces(s.mentors_root)
    git_exe = shutil.which("git")
    cloned = False
    for name in sorted(referenced):
        dest = s.marketplaces_root / name
        if dest.exists():
            continue
        url = s.marketplace_repos.get(name)
        if not url:
            logger.warning(
                "marketplace %r is referenced by the corpus but absent from "
                "AMMP_MARKETPLACE_REPOS — its skill bodies will be unavailable",
                name,
            )
            continue
        if git_exe is None:
            logger.warning("git not found on PATH — cannot clone marketplace %r", name)
            continue
        s.marketplaces_root.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            [git_exe, "clone", "--depth", "1", url, str(dest)],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            cloned = True
            if not quiet:
                console.print(f"{_ICON_OK} Cloned marketplace [bold]{name}[/bold] ← {url}")
        else:
            logger.warning("marketplace %r clone failed (%s): %s", name, url, result.stderr.strip()[:200])
    return cloned


def _setup_print_header(s: Settings) -> None:
    """Render the Step-0 environment panel for the ``ammp setup`` wizard.

    Args:
        s: The resolved Settings whose paths get echoed back so the
            operator can confirm them before any disk writes happen.
    """
    console.print(
        Panel.fit(
            f"[bold]ammp-mcp setup[/bold]\n"
            f"[dim]ammp_dir:[/dim] {s.ammp_dir}\n"
            f"[dim]mentors_root:[/dim] {s.mentors_root}\n"
            f"[dim]mentees_file:[/dim] {s.mentees_file}\n"
            f"[dim]audit_log:[/dim] {s.audit_log_path}",
            title="Step 0 — environment",
            border_style="cyan",
        )
    )


def _setup_validate(mentors_root: Path, mentor_slug: str, backend: str) -> dict[str, Mentor]:
    """Pre-flight the wizard inputs before any disk write happens.

    Args:
        mentors_root: Directory expected to contain
            ``<mentor_slug>/mentor.json``.
        mentor_slug: The slug the operator chose to configure.
        backend: The backend kind they want to write; must be one of
            ``"anthropic"``, ``"openclaw"``, ``"stub"``.

    Returns:
        The full mentor registry loaded from disk, ready for downstream
        use.

    Raises:
        typer.Exit: Exit code 2 when the mentor directory is missing
            or when the backend kind is unknown.
    """
    mentors = load_mentors(mentors_root)
    if mentor_slug not in mentors:
        console.print(
            f"[red]No mentor directory found at {mentors_root / mentor_slug}.[/red]\n"
            "Create one with `mentor.json` + `playbooks/*.md` first, then re-run setup."
        )
        raise typer.Exit(code=2)
    if backend not in _VALID_BACKEND_KINDS:
        kinds = ", ".join(sorted(_VALID_BACKEND_KINDS))
        console.print(f"[red]Unknown backend kind: {backend!r}. Choose one of: {kinds}.[/red]")
        raise typer.Exit(code=2)
    return mentors


def _setup_resolve_openclaw_args(yes: bool, openclaw_url: str, auth_bearer_env: str) -> tuple[str, str]:
    """Either echo the openclaw-backend defaults or prompt the operator for them.

    Args:
        yes: When ``True``, skip prompts and use the defaults as-is
            (``ammp setup --yes``).
        openclaw_url: Default OpenClaw webhook URL to suggest.
        auth_bearer_env: Default env-var name for the Bearer token.

    Returns:
        A ``(url, bearer_env_name)`` tuple — either the input defaults
        unchanged (``--yes`` mode) or whatever the operator typed.
    """
    if yes:
        return openclaw_url, auth_bearer_env
    url = Prompt.ask("OpenClaw webhook URL", default=openclaw_url, console=console)
    bearer = Prompt.ask("Env var holding the OpenClaw Bearer token", default=auth_bearer_env, console=console)
    return url, bearer


def _setup_apply_backend(mentor_json_path: Path, backend: str, openclaw_url: str, auth_bearer_env: str) -> None:
    """Rewrite a ``mentor.json`` file with the chosen backend block.

    Idempotent — re-running with the same arguments produces an
    identical file. Underscore-prefixed JSON keys (intent hints) are
    stripped from the existing file before the merge.

    Args:
        mentor_json_path: Path to the existing ``mentor.json`` to update.
        backend: Backend kind (``"anthropic"``, ``"openclaw"``, or
            ``"stub"``).
        openclaw_url: Webhook URL (only used when ``backend == "openclaw"``).
        auth_bearer_env: Env var name for the Bearer token (only used
            when ``backend == "openclaw"``).
    """
    backend_block: dict[str, object] = {"kind": backend}
    if backend == "openclaw":
        backend_block.update(
            {"url": openclaw_url, "auth_bearer_env": auth_bearer_env, "timeout_seconds": 60, "max_concurrent": 10}
        )
    raw = json.loads(mentor_json_path.read_text(encoding="utf-8"))
    raw = {k: v for k, v in raw.items() if not k.startswith("_")}
    raw["backend"] = backend_block
    mentor_json_path.write_text(json.dumps(raw, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _setup_mint_mentee_if_needed(mentees_file: Path) -> str | None:
    """Mint a first mentee (``claude-cowork-helmut``) when one is not already present.

    Args:
        mentees_file: Path to the JSON allowlist. Created on demand.

    Returns:
        The freshly-minted plaintext API key (shown to the operator
        once and then discarded), or ``None`` when the mentee already
        existed and was therefore left untouched.
    """
    mentees = load_mentees(mentees_file) if mentees_file.exists() else {}
    first_slug = "claude-cowork-helmut"
    if first_slug in mentees:
        console.print(f"[yellow]·[/yellow] Mentee [bold]{first_slug}[/bold] already exists — skipped.")
        return None
    api_key = "ammp-" + secrets.token_urlsafe(32)
    mentees[first_slug] = Mentee(
        slug=first_slug,
        operator="human:helmut",
        runtime="claude-cowork",
        api_key_hash=hash_api_key(api_key),
        rate_limit_per_minute=60,
    )
    save_mentees(mentees_file, mentees)
    console.print(f"{_ICON_OK} Minted first mentee [bold]{first_slug}[/bold].")
    return api_key


def _setup_load_existing_env(env_path: Path) -> dict[str, str]:
    """Parse an existing ``.env``-style file into a ``key -> value`` dict.

    Comments (``#`` lines) and blank lines are skipped. Values are
    returned verbatim — no unquoting, no variable interpolation. Used
    only to preserve operator-edited keys (typically secrets) across
    wizard re-runs.

    Args:
        env_path: Path to the env file. A missing file yields an empty
            dict, not an error.

    Returns:
        Mapping of env-var names to their string values, with whitespace
        trimmed off both sides.
    """
    if not env_path.exists():
        return {}
    out: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.strip().startswith("#"):
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip()
    return out


def _setup_compose_env(
    s: Settings, backend: str, auth_bearer_env: str, require_auth: bool, existing: dict[str, str]
) -> dict[str, str]:
    """Merge wizard choices on top of an existing env-file's keys.

    The wizard's chosen values WIN over anything in ``existing`` — the
    older file only carries forward keys the wizard does not set
    (typically operator-edited secrets and custom env vars).

    Args:
        s: The resolved Settings whose paths get written into the file.
        backend: Chosen backend kind (``"anthropic"`` / ``"openclaw"`` /
            ``"stub"``).
        auth_bearer_env: Env-var name holding the openclaw Bearer token
            (only meaningful when ``backend == "openclaw"``).
        require_auth: Whether to flip ``AMMP_REQUIRE_AUTH`` to ``"true"``
            in the written file.
        existing: Existing key/value pairs to merge under the wizard's
            choices (typically from :func:`_setup_load_existing_env`).

    Returns:
        Merged mapping ready for :func:`_setup_write_env`.
    """
    desired = {
        "AMMP_DIR": str(s.ammp_dir),
        "AMMP_REQUIRE_AUTH": "true" if require_auth else "false",
        "AMMP_MENTORS_ROOT": str(s.mentors_root),
        "AMMP_MENTEES_FILE": str(s.mentees_file),
        "AMMP_AUDIT_LOG_PATH": str(s.audit_log_path),
    }
    if backend == "anthropic":
        desired.setdefault("AMMP_ANTHROPIC_API_KEY", existing.get("AMMP_ANTHROPIC_API_KEY", ""))
    if backend == "openclaw":
        desired.setdefault(auth_bearer_env, existing.get(auth_bearer_env, ""))
    # The wizard's choices override what bootstrap or a previous run wrote;
    # `existing` only carries forward keys `desired` doesn't set (typically
    # operator-edited secrets and custom keys).
    return {**existing, **desired}


def _setup_write_env(env_path: Path, merged: dict[str, str], auth_bearer_env: str) -> None:
    """Render a merged env dict to a ``.env``-style file on disk.

    Adds a header comment with timestamp; appends inline ``# fill in
    …`` hints for known-secret keys whose values are still empty.
    Creates parent directories if needed.

    Args:
        env_path: Destination file path. Parent directories are
            created on demand.
        merged: The env-var mapping to write (typically the output of
            :func:`_setup_compose_env`).
        auth_bearer_env: The openclaw-bearer env-var name — used to
            decide which empty value to flag with a "fill in" hint.
    """
    lines = [
        "# ammp-mcp config — written by `ammp setup`. Edit freely.",
        f"# Generated {dt.datetime.now(dt.UTC).isoformat()}.",
        "",
    ]
    for k in sorted(merged):
        v = merged[k]
        comment = ""
        if k == auth_bearer_env and not v:
            comment = "  # <-- fill in the Bearer token before booting"
        if k == "AMMP_ANTHROPIC_API_KEY" and not v:
            comment = "  # <-- fill in if you choose the anthropic backend"
        lines.append(f"{k}={v}{comment}")
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    console.print(f"{_ICON_OK} Wrote [bold]{env_path}[/bold] ({len(merged)} keys).")


def _setup_print_next_steps(backend: str, auth_bearer_env: str) -> None:
    """Print the closing "Next steps" panel of the ``ammp setup`` wizard.

    Args:
        backend: Chosen backend kind — drives which secret env var the
            operator is told to fill in.
        auth_bearer_env: Env-var name holding the openclaw Bearer token
            (used only when ``backend == "openclaw"``).
    """
    next_secret = auth_bearer_env if backend == "openclaw" else "AMMP_ANTHROPIC_API_KEY"
    console.print()
    console.print(
        Panel.fit(
            "[bold]Next steps[/bold]\n\n"
            f"  1. Edit [cyan]~/.ammp/config.env[/cyan] and fill in the [cyan]{next_secret}[/cyan] value.\n"
            "  2. [cyan]ammp status[/cyan] — verify the install is healthy.\n"
            "  3. [cyan]ammp serve[/cyan] — boot the MCP server.\n"
            "  4. [cyan]curl http://127.0.0.1:8765/.well-known/agent.json[/cyan] — confirm the capability advertisement.",
            title="Setup complete",
            border_style="green",
        )
    )
